CREATE TABLE channels (
    id VARCHAR(32) PRIMARY KEY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id VARCHAR(32) PRIMARY KEY NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE channels_users (
    user_id VARCHAR(32) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    channel_id VARCHAR(32) REFERENCES channels(id) ON UPDATE CASCADE ON DELETE CASCADE,
    activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, channel_id)
);